import type { Metadata } from "next"
import { auth } from "@/auth";
import { Inter, Poppins } from "next/font/google"
import { SessionProvider } from "next-auth/react"
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["600"],
  variable: "--font-poppins"
})

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth()

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body
          className={`
            ${inter.className} 
            ${poppins.variable} 
            bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-sky-400 to-blue-800`}
        >
          <Toaster />
          {children}
        </body>
      </html>
    </SessionProvider>
  )
}
